const Symbol = require("../models/Symbol");
const User = require("../models/User"); // Replace with the actual path to the User model
const bcrypt = require("bcrypt");

const lettersData = [
  {
    character: "u1200",
    representation: "ሀ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1201",
    representation: "ሁ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1202",
    representation: "ሂ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1203",
    representation: "ሃ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1204",
    representation: "ሄ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1205",
    representation: "ህ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1206",
    representation: "ሆ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1208",
    representation: "ለ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1209",
    representation: "ሉ",
    type: "letter",
    form: 2,
  },
  {
    character: "u120a",
    representation: "ሊ",
    type: "letter",
    form: 3,
  },
  {
    character: "u120b",
    representation: "ላ",
    type: "letter",
    form: 4,
  },
  {
    character: "u120c",
    representation: "ሌ",
    type: "letter",
    form: 5,
  },
  {
    character: "u120d",
    representation: "ል",
    type: "letter",
    form: 6,
  },
  {
    character: "u120e",
    representation: "ሎ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1210",
    representation: "ሐ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1211",
    representation: "ሑ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1212",
    representation: "ሒ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1213",
    representation: "ሓ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1214",
    representation: "ሔ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1215",
    representation: "ሕ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1216",
    representation: "ሖ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1218",
    representation: "መ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1219",
    representation: "ሙ",
    type: "letter",
    form: 2,
  },
  {
    character: "u121a",
    representation: "ሚ",
    type: "letter",
    form: 3,
  },
  {
    character: "u121b",
    representation: "ማ",
    type: "letter",
    form: 4,
  },
  {
    character: "u121c",
    representation: "ሜ",
    type: "letter",
    form: 5,
  },
  {
    character: "u121d",
    representation: "ም",
    type: "letter",
    form: 6,
  },
  {
    character: "u121e",
    representation: "ሞ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1220",
    representation: "ሠ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1221",
    representation: "ሡ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1222",
    representation: "ሢ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1223",
    representation: "ሣ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1224",
    representation: "ሤ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1225",
    representation: "ሥ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1226",
    representation: "ሦ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1228",
    representation: "ረ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1229",
    representation: "ሩ",
    type: "letter",
    form: 2,
  },
  {
    character: "u122a",
    representation: "ሪ",
    type: "letter",
    form: 3,
  },
  {
    character: "u122b",
    representation: "ራ",
    type: "letter",
    form: 4,
  },
  {
    character: "u122c",
    representation: "ሬ",
    type: "letter",
    form: 5,
  },
  {
    character: "u122d",
    representation: "ር",
    type: "letter",
    form: 6,
  },
  {
    character: "u122e",
    representation: "ሮ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1230",
    representation: "ሰ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1231",
    representation: "ሱ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1232",
    representation: "ሲ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1233",
    representation: "ሳ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1234",
    representation: "ሴ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1235",
    representation: "ስ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1236",
    representation: "ሶ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1238",
    representation: "ሸ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1239",
    representation: "ሹ",
    type: "letter",
    form: 2,
  },
  {
    character: "u123a",
    representation: "ሺ",
    type: "letter",
    form: 3,
  },
  {
    character: "u123b",
    representation: "ሻ",
    type: "letter",
    form: 4,
  },
  {
    character: "u123c",
    representation: "ሼ",
    type: "letter",
    form: 5,
  },
  {
    character: "u123d",
    representation: "ሽ",
    type: "letter",
    form: 6,
  },
  {
    character: "u123e",
    representation: "ሾ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1240",
    representation: "ቀ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1241",
    representation: "ቁ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1242",
    representation: "ቂ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1243",
    representation: "ቃ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1244",
    representation: "ቄ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1245",
    representation: "ቅ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1246",
    representation: "ቆ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1260",
    representation: "በ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1261",
    representation: "ቡ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1262",
    representation: "ቢ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1263",
    representation: "ባ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1264",
    representation: "ቤ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1265",
    representation: "ብ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1266",
    representation: "ቦ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1268",
    representation: "ቨ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1269",
    representation: "ቩ",
    type: "letter",
    form: 2,
  },
  {
    character: "u126a",
    representation: "ቪ",
    type: "letter",
    form: 3,
  },
  {
    character: "u126b",
    representation: "ቫ",
    type: "letter",
    form: 4,
  },
  {
    character: "u126c",
    representation: "ቬ",
    type: "letter",
    form: 5,
  },
  {
    character: "u126d",
    representation: "ቭ",
    type: "letter",
    form: 6,
  },
  {
    character: "u126e",
    representation: "ቮ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1270",
    representation: "ተ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1271",
    representation: "ቱ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1272",
    representation: "ቲ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1273",
    representation: "ታ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1274",
    representation: "ቴ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1275",
    representation: "ት",
    type: "letter",
    form: 6,
  },
  {
    character: "u1276",
    representation: "ቶ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1278",
    representation: "ቸ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1279",
    representation: "ቹ",
    type: "letter",
    form: 2,
  },
  {
    character: "u127a",
    representation: "ቺ",
    type: "letter",
    form: 3,
  },
  {
    character: "u127b",
    representation: "ቻ",
    type: "letter",
    form: 4,
  },
  {
    character: "u127c",
    representation: "ቼ",
    type: "letter",
    form: 5,
  },
  {
    character: "u127d",
    representation: "ች",
    type: "letter",
    form: 6,
  },
  {
    character: "u127e",
    representation: "ቾ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1280",
    representation: "ኀ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1281",
    representation: "ኁ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1282",
    representation: "ኂ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1283",
    representation: "ኃ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1284",
    representation: "ኄ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1285",
    representation: "ኅ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1286",
    representation: "ኆ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1290",
    representation: "ነ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1291",
    representation: "ኑ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1292",
    representation: "ኒ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1293",
    representation: "ና",
    type: "letter",
    form: 4,
  },
  {
    character: "u1294",
    representation: "ኔ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1295",
    representation: "ን",
    type: "letter",
    form: 6,
  },
  {
    character: "u1296",
    representation: "ኖ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1298",
    representation: "ኘ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1299",
    representation: "ኙ",
    type: "letter",
    form: 2,
  },
  {
    character: "u129a",
    representation: "ኚ",
    type: "letter",
    form: 3,
  },
  {
    character: "u129b",
    representation: "ኛ",
    type: "letter",
    form: 4,
  },
  {
    character: "u129c",
    representation: "ኜ",
    type: "letter",
    form: 5,
  },
  {
    character: "u129d",
    representation: "ኝ",
    type: "letter",
    form: 6,
  },
  {
    character: "u129e",
    representation: "ኞ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12a0",
    representation: "አ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12a1",
    representation: "ኡ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12a2",
    representation: "ኢ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12a3",
    representation: "ኣ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12a4",
    representation: "ኤ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12a5",
    representation: "እ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12a6",
    representation: "ኦ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12a8",
    representation: "ከ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12a9",
    representation: "ኩ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12aa",
    representation: "ኪ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12ab",
    representation: "ካ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12ac",
    representation: "ኬ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12ad",
    representation: "ክ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12ae",
    representation: "ኮ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12b8",
    representation: "ኸ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12b9",
    representation: "ኹ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12ba",
    representation: "ኺ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12bb",
    representation: "ኻ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12bc",
    representation: "ኼ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12bd",
    representation: "ኽ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12be",
    representation: "ኾ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12c0",
    representation: "ዀ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12c8",
    representation: "ወ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12c9",
    representation: "ዉ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12ca",
    representation: "ዊ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12cb",
    representation: "ዋ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12cc",
    representation: "ዌ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12cd",
    representation: "ው",
    type: "letter",
    form: 6,
  },
  {
    character: "u12ce",
    representation: "ዎ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12d0",
    representation: "ዐ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12d1",
    representation: "ዑ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12d2",
    representation: "ዒ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12d3",
    representation: "ዓ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12d4",
    representation: "ዔ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12d5",
    representation: "ዕ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12d6",
    representation: "ዖ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12d8",
    representation: "ዘ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12d9",
    representation: "ዙ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12da",
    representation: "ዚ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12db",
    representation: "ዛ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12dc",
    representation: "ዜ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12dd",
    representation: "ዝ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12de",
    representation: "ዞ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12e0",
    representation: "ዠ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12e1",
    representation: "ዡ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12e2",
    representation: "ዢ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12e3",
    representation: "ዣ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12e4",
    representation: "ዤ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12e5",
    representation: "ዥ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12e6",
    representation: "ዦ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12e8",
    representation: "የ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12e9",
    representation: "ዩ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12ea",
    representation: "ዪ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12eb",
    representation: "ያ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12ec",
    representation: "ዬ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12ed",
    representation: "ይ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12ee",
    representation: "ዮ",
    type: "letter",
    form: 7,
  },
  {
    character: "u12f0",
    representation: "ደ",
    type: "letter",
    form: 1,
  },
  {
    character: "u12f1",
    representation: "ዱ",
    type: "letter",
    form: 2,
  },
  {
    character: "u12f2",
    representation: "ዲ",
    type: "letter",
    form: 3,
  },
  {
    character: "u12f3",
    representation: "ዳ",
    type: "letter",
    form: 4,
  },
  {
    character: "u12f4",
    representation: "ዴ",
    type: "letter",
    form: 5,
  },
  {
    character: "u12f5",
    representation: "ድ",
    type: "letter",
    form: 6,
  },
  {
    character: "u12f6",
    representation: "ዶ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1300",
    representation: "ጀ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1301",
    representation: "ጁ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1302",
    representation: "ጂ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1303",
    representation: "ጃ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1304",
    representation: "ጄ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1305",
    representation: "ጅ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1306",
    representation: "ጆ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1308",
    representation: "ገ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1309",
    representation: "ጉ",
    type: "letter",
    form: 2,
  },
  {
    character: "u130a",
    representation: "ጊ",
    type: "letter",
    form: 3,
  },
  {
    character: "u130b",
    representation: "ጋ",
    type: "letter",
    form: 4,
  },
  {
    character: "u130c",
    representation: "ጌ",
    type: "letter",
    form: 5,
  },
  {
    character: "u130d",
    representation: "ግ",
    type: "letter",
    form: 6,
  },
  {
    character: "u130e",
    representation: "ጎ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1320",
    representation: "ጠ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1321",
    representation: "ጡ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1322",
    representation: "ጢ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1323",
    representation: "ጣ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1324",
    representation: "ጤ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1325",
    representation: "ጥ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1326",
    representation: "ጦ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1328",
    representation: "ጨ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1329",
    representation: "ጩ",
    type: "letter",
    form: 2,
  },
  {
    character: "u132a",
    representation: "ጪ",
    type: "letter",
    form: 3,
  },
  {
    character: "u132b",
    representation: "ጫ",
    type: "letter",
    form: 4,
  },
  {
    character: "u132c",
    representation: "ጬ",
    type: "letter",
    form: 5,
  },
  {
    character: "u132d",
    representation: "ጭ",
    type: "letter",
    form: 6,
  },
  {
    character: "u132e",
    representation: "ጮ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1330",
    representation: "ጰ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1331",
    representation: "ጱ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1332",
    representation: "ጲ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1333",
    representation: "ጳ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1334",
    representation: "ጴ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1335",
    representation: "ጵ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1336",
    representation: "ጶ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1338",
    representation: "ጸ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1339",
    representation: "ጹ",
    type: "letter",
    form: 2,
  },
  {
    character: "u133a",
    representation: "ጺ",
    type: "letter",
    form: 3,
  },
  {
    character: "u133b",
    representation: "ጻ",
    type: "letter",
    form: 4,
  },
  {
    character: "u133c",
    representation: "ጼ",
    type: "letter",
    form: 5,
  },
  {
    character: "u133d",
    representation: "ጽ",
    type: "letter",
    form: 6,
  },
  {
    character: "u133e",
    representation: "ጾ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1340",
    representation: "ፀ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1341",
    representation: "ፁ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1342",
    representation: "ፂ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1343",
    representation: "ፃ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1344",
    representation: "ፄ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1345",
    representation: "ፅ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1346",
    representation: "ፆ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1348",
    representation: "ፈ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1349",
    representation: "ፉ",
    type: "letter",
    form: 2,
  },
  {
    character: "u134a",
    representation: "ፊ",
    type: "letter",
    form: 3,
  },
  {
    character: "u134b",
    representation: "ፋ",
    type: "letter",
    form: 4,
  },
  {
    character: "u134c",
    representation: "ፌ",
    type: "letter",
    form: 5,
  },
  {
    character: "u134d",
    representation: "ፍ",
    type: "letter",
    form: 6,
  },
  {
    character: "u134e",
    representation: "ፎ",
    type: "letter",
    form: 7,
  },
  {
    character: "u1350",
    representation: "ፐ",
    type: "letter",
    form: 1,
  },
  {
    character: "u1351",
    representation: "ፑ",
    type: "letter",
    form: 2,
  },
  {
    character: "u1352",
    representation: "ፒ",
    type: "letter",
    form: 3,
  },
  {
    character: "u1353",
    representation: "ፓ",
    type: "letter",
    form: 4,
  },
  {
    character: "u1354",
    representation: "ፔ",
    type: "letter",
    form: 5,
  },
  {
    character: "u1355",
    representation: "ፕ",
    type: "letter",
    form: 6,
  },
  {
    character: "u1356",
    representation: "ፖ",
    type: "letter",
    form: 7,
  },
];
const migrateLetters = async () => {
  const existingSymbolsCount = await Symbol.countDocuments();

  if (existingSymbolsCount === lettersData.length) {
    console.log("Symbols already migrated, skipping...");
    return;
  }

  let lettersCount = 0;

  for (const letterData of lettersData) {
    const { character } = letterData;
    const letter = await Symbol.findOne({ character });
    if (!letter) {
      await Symbol.create(letterData);
      lettersCount += 1;
    }
  }

  console.log(`Migration of ${lettersCount} letters completed!`);
};

let usersCount = 0;
const usersData = [
  {
    firstName: "User",
    lastName: "One",
    username: "User1",
    phone: "1234567890",
    email: "user1@example.com",
    password: bcrypt.hashSync("userPassword", 10),
    role: "user",
  },
  {
    firstName: "Admin",
    lastName: "One",
    username: "Admin1",
    phone: "1234567891",
    email: "admin1@example.com",
    password: bcrypt.hashSync("adminPassword", 10),
    role: "admin",
  },
  {
    firstName: "Mod",
    lastName: "One",
    username: "Mod1",
    phone: "1234567892",
    email: "mod1@example.com",
    password: bcrypt.hashSync("moderatorPassword", 10),
    role: "moderator",
  },
];
const migrateUsers = async () => {
  for (const userData of usersData) {
    const { email } = userData;
    const user = await User.findOne({ email });
    if (!user) {
      await User.create(userData);
      usersCount += 1;
    }
  }
  console.log(`Migration of ${usersCount} users completed!`);
};

const migrate = async () => {
  await migrateLetters();
  await migrateUsers();
};

module.exports = migrate;
